[advisories]
ignore = []

[licenses]
allow = [
  "GPL-2.0-only",
  "0BSD",
  "MIT",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
