[package]
name = "rondi-cli"
description = "RRDtool-compatible command-line interface and Rondi server executable"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[[bin]]
name = "rondi"
path = "src/main.rs"
doc = false

[dependencies]
rondi = { path = "../rondi" }
rondi-server = { path = "../rondi-server" }
clap.workspace = true
glob.workspace = true
serde_json.workspace = true
tokio.workspace = true
bytes.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
libc.workspace = true
png = "0.18"
font8x8 = "0.3"

[dev-dependencies]
tempfile = "3"
